SET(CPLEX_ROOT_DIR "" CACHE PATH "CPLEX root directory")
SET(CONCERT_ROOT_DIR "" CACHE PATH "CONCERT root directory")

FIND_PATH(CPLEX_INCLUDE_DIR
  ilcplex/cplex.h
  HINTS ${CPLEX_ROOT_DIR}/include
  )

FIND_PATH(CONCERT_INCLUDE_DIR
  ilconcert/iloenv.h
  HINTS ${CONCERT_ROOT_DIR}/include
  )

FIND_LIBRARY(CPLEX_LIBRARY
  cplex
  HINTS ${CPLEX_ROOT_DIR}/bin
  )

FIND_LIBRARY(ILOCPLEX_LIBRARY
  ilocplex
  HINTS ${CPLEX_ROOT_DIR}/bin
  )

FIND_LIBRARY(CONCERT_LIBRARY
  concert
  HINTS ${CONCERT_ROOT_DIR}/bin
  )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPLEX DEFAULT_MSG CPLEX_LIBRARY CPLEX_INCLUDE_DIR)

IF(CPLEX_FOUND)
  SET(CPLEX_INCLUDE_DIRS ${CPLEX_INCLUDE_DIR} ${CONCERT_INCLUDE_DIR})
  SET(CPLEX_LIBRARIES ${CPLEX_LIBRARY} ${ILOCPLEX_LIBRARY} ${CONCERT_LIBRARY})
  IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    SET(CPLEX_LIBRARIES "${CPLEX_LIBRARIES};m;pthread")
  ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
ENDIF(CPLEX_FOUND)

MARK_AS_ADVANCED(CPLEX_INCLUDE_DIRS CPLEX_LIBRARIES)
